name: Log Kubernetes Resources

on:
  push:

jobs:
  log-k8s-resources:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Install CloudNative PG
      run: |
        helm repo add cnpg https://cloudnative-pg.github.io/charts
        helm upgrade --install cnpg \
          --namespace cnpg-system \
          --create-namespace \
          cnpg/cloudnative-pg
