name: Log Kubernetes Resources

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering
jobs:
  create_pull_secrets:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        namespace: [default, ada]
      fail-fast: false # Continue with other namespaces if one fails

    steps:
      - uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - run: |
          kubectl create secret docker-registry docker-pull-secret \
            --docker-server=ghcr.io \
            --docker-username=${{ github.actor }} \
            --docker-password=${{ secrets.GHRC_PULL_TOKEN }} \
            --namespace ${{ matrix.namespace }} \
            --dry-run=client -o yaml | kubectl apply -f -

  deploy_pg_native:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Install CloudNative PG
        run: |
          helm repo add cnpg https://cloudnative-pg.github.io/charts
          helm repo update
          helm upgrade --install cnpg \
            --namespace cnpg-system \
            --create-namespace \
            --wait \
            --timeout 5m \
            --atomic \
            cnpg/cloudnative-pg

  deploy_elastic_search:
    runs-on: ubuntu-latest

    steps:
      - uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Install Elastic Searcs
        run: |
          helm upgrade --install elastic-search \
            --namespace default \
            --values ./elasticsearch.values.yaml \
            --wait \
            --atomic \
            oci://registry-1.docker.io/bitnamicharts/elasticsearch
