name: Log Kubernetes Resources

on:
  push:

jobs:
  log-k8s-resources:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Log all resources in the cluster
      run: kubectl get all --all-namespaces